# Generated by Django 4.1.3 on 2022-11-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_g', models.CharField(blank=True, default='g', max_length=50, null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('paid', models.BooleanField()),
                ('order_no', models.CharField(max_length=60)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ourcart',
                'verbose_name_plural': 'Ourcart',
                'db_table': 'ourcart',
                'managed': True,
            },
        ),
    ]
