# Generated by Django 4.1.3 on 2022-11-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': True, 'verbose_name': 'Cart', 'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
    ]
